import Quartic.FiniteEndpointInverseMemo24
import Quartic.FiniteEndpointMetadata24Data

/-! Kernel-checked rows of the actual quartic multiplication matrix. -/
namespace Quartic.FiniteEndpointRows24
open FiniteEndpointChecker
set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 64000000

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 0 row_count 64

theorem chunk_0 (i : Fin 64) (hi : 0+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (0+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(0+i.val) := by
  fin_cases i
  · exact certificate.row_0
  · exact certificate.row_1
  · exact certificate.row_2
  · exact certificate.row_3
  · exact certificate.row_4
  · exact certificate.row_5
  · exact certificate.row_6
  · exact certificate.row_7
  · exact certificate.row_8
  · exact certificate.row_9
  · exact certificate.row_10
  · exact certificate.row_11
  · exact certificate.row_12
  · exact certificate.row_13
  · exact certificate.row_14
  · exact certificate.row_15
  · exact certificate.row_16
  · exact certificate.row_17
  · exact certificate.row_18
  · exact certificate.row_19
  · exact certificate.row_20
  · exact certificate.row_21
  · exact certificate.row_22
  · exact certificate.row_23
  · exact certificate.row_24
  · exact certificate.row_25
  · exact certificate.row_26
  · exact certificate.row_27
  · exact certificate.row_28
  · exact certificate.row_29
  · exact certificate.row_30
  · exact certificate.row_31
  · exact certificate.row_32
  · exact certificate.row_33
  · exact certificate.row_34
  · exact certificate.row_35
  · exact certificate.row_36
  · exact certificate.row_37
  · exact certificate.row_38
  · exact certificate.row_39
  · exact certificate.row_40
  · exact certificate.row_41
  · exact certificate.row_42
  · exact certificate.row_43
  · exact certificate.row_44
  · exact certificate.row_45
  · exact certificate.row_46
  · exact certificate.row_47
  · exact certificate.row_48
  · exact certificate.row_49
  · exact certificate.row_50
  · exact certificate.row_51
  · exact certificate.row_52
  · exact certificate.row_53
  · exact certificate.row_54
  · exact certificate.row_55
  · exact certificate.row_56
  · exact certificate.row_57
  · exact certificate.row_58
  · exact certificate.row_59
  · exact certificate.row_60
  · exact certificate.row_61
  · exact certificate.row_62
  · exact certificate.row_63

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 64 row_count 64

theorem chunk_1 (i : Fin 64) (hi : 64+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (64+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(64+i.val) := by
  fin_cases i
  · exact certificate.row_64
  · exact certificate.row_65
  · exact certificate.row_66
  · exact certificate.row_67
  · exact certificate.row_68
  · exact certificate.row_69
  · exact certificate.row_70
  · exact certificate.row_71
  · exact certificate.row_72
  · exact certificate.row_73
  · exact certificate.row_74
  · exact certificate.row_75
  · exact certificate.row_76
  · exact certificate.row_77
  · exact certificate.row_78
  · exact certificate.row_79
  · exact certificate.row_80
  · exact certificate.row_81
  · exact certificate.row_82
  · exact certificate.row_83
  · exact certificate.row_84
  · exact certificate.row_85
  · exact certificate.row_86
  · exact certificate.row_87
  · exact certificate.row_88
  · exact certificate.row_89
  · exact certificate.row_90
  · exact certificate.row_91
  · exact certificate.row_92
  · exact certificate.row_93
  · exact certificate.row_94
  · exact certificate.row_95
  · exact certificate.row_96
  · exact certificate.row_97
  · exact certificate.row_98
  · exact certificate.row_99
  · exact certificate.row_100
  · exact certificate.row_101
  · exact certificate.row_102
  · exact certificate.row_103
  · exact certificate.row_104
  · exact certificate.row_105
  · exact certificate.row_106
  · exact certificate.row_107
  · exact certificate.row_108
  · exact certificate.row_109
  · exact certificate.row_110
  · exact certificate.row_111
  · exact certificate.row_112
  · exact certificate.row_113
  · exact certificate.row_114
  · exact certificate.row_115
  · exact certificate.row_116
  · exact certificate.row_117
  · exact certificate.row_118
  · exact certificate.row_119
  · exact certificate.row_120
  · exact certificate.row_121
  · exact certificate.row_122
  · exact certificate.row_123
  · exact certificate.row_124
  · exact certificate.row_125
  · exact certificate.row_126
  · exact certificate.row_127

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 128 row_count 64

theorem chunk_2 (i : Fin 64) (hi : 128+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (128+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(128+i.val) := by
  fin_cases i
  · exact certificate.row_128
  · exact certificate.row_129
  · exact certificate.row_130
  · exact certificate.row_131
  · exact certificate.row_132
  · exact certificate.row_133
  · exact certificate.row_134
  · exact certificate.row_135
  · exact certificate.row_136
  · exact certificate.row_137
  · exact certificate.row_138
  · exact certificate.row_139
  · exact certificate.row_140
  · exact certificate.row_141
  · exact certificate.row_142
  · exact certificate.row_143
  · exact certificate.row_144
  · exact certificate.row_145
  · exact certificate.row_146
  · exact certificate.row_147
  · exact certificate.row_148
  · exact certificate.row_149
  · exact certificate.row_150
  · exact certificate.row_151
  · exact certificate.row_152
  · exact certificate.row_153
  · exact certificate.row_154
  · exact certificate.row_155
  · exact certificate.row_156
  · exact certificate.row_157
  · exact certificate.row_158
  · exact certificate.row_159
  · exact certificate.row_160
  · exact certificate.row_161
  · exact certificate.row_162
  · exact certificate.row_163
  · exact certificate.row_164
  · exact certificate.row_165
  · exact certificate.row_166
  · exact certificate.row_167
  · exact certificate.row_168
  · exact certificate.row_169
  · exact certificate.row_170
  · exact certificate.row_171
  · exact certificate.row_172
  · exact certificate.row_173
  · exact certificate.row_174
  · exact certificate.row_175
  · exact certificate.row_176
  · exact certificate.row_177
  · exact certificate.row_178
  · exact certificate.row_179
  · exact certificate.row_180
  · exact certificate.row_181
  · exact certificate.row_182
  · exact certificate.row_183
  · exact certificate.row_184
  · exact certificate.row_185
  · exact certificate.row_186
  · exact certificate.row_187
  · exact certificate.row_188
  · exact certificate.row_189
  · exact certificate.row_190
  · exact certificate.row_191

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 192 row_count 64

theorem chunk_3 (i : Fin 64) (hi : 192+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (192+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(192+i.val) := by
  fin_cases i
  · exact certificate.row_192
  · exact certificate.row_193
  · exact certificate.row_194
  · exact certificate.row_195
  · exact certificate.row_196
  · exact certificate.row_197
  · exact certificate.row_198
  · exact certificate.row_199
  · exact certificate.row_200
  · exact certificate.row_201
  · exact certificate.row_202
  · exact certificate.row_203
  · exact certificate.row_204
  · exact certificate.row_205
  · exact certificate.row_206
  · exact certificate.row_207
  · exact certificate.row_208
  · exact certificate.row_209
  · exact certificate.row_210
  · exact certificate.row_211
  · exact certificate.row_212
  · exact certificate.row_213
  · exact certificate.row_214
  · exact certificate.row_215
  · exact certificate.row_216
  · exact certificate.row_217
  · exact certificate.row_218
  · exact certificate.row_219
  · exact certificate.row_220
  · exact certificate.row_221
  · exact certificate.row_222
  · exact certificate.row_223
  · exact certificate.row_224
  · exact certificate.row_225
  · exact certificate.row_226
  · exact certificate.row_227
  · exact certificate.row_228
  · exact certificate.row_229
  · exact certificate.row_230
  · exact certificate.row_231
  · exact certificate.row_232
  · exact certificate.row_233
  · exact certificate.row_234
  · exact certificate.row_235
  · exact certificate.row_236
  · exact certificate.row_237
  · exact certificate.row_238
  · exact certificate.row_239
  · exact certificate.row_240
  · exact certificate.row_241
  · exact certificate.row_242
  · exact certificate.row_243
  · exact certificate.row_244
  · exact certificate.row_245
  · exact certificate.row_246
  · exact certificate.row_247
  · exact certificate.row_248
  · exact certificate.row_249
  · exact certificate.row_250
  · exact certificate.row_251
  · exact certificate.row_252
  · exact certificate.row_253
  · exact certificate.row_254
  · exact certificate.row_255

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 256 row_count 64

theorem chunk_4 (i : Fin 64) (hi : 256+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (256+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(256+i.val) := by
  fin_cases i
  · exact certificate.row_256
  · exact certificate.row_257
  · exact certificate.row_258
  · exact certificate.row_259
  · exact certificate.row_260
  · exact certificate.row_261
  · exact certificate.row_262
  · exact certificate.row_263
  · exact certificate.row_264
  · exact certificate.row_265
  · exact certificate.row_266
  · exact certificate.row_267
  · exact certificate.row_268
  · exact certificate.row_269
  · exact certificate.row_270
  · exact certificate.row_271
  · exact certificate.row_272
  · exact certificate.row_273
  · exact certificate.row_274
  · exact certificate.row_275
  · exact certificate.row_276
  · exact certificate.row_277
  · exact certificate.row_278
  · exact certificate.row_279
  · exact certificate.row_280
  · exact certificate.row_281
  · exact certificate.row_282
  · exact certificate.row_283
  · exact certificate.row_284
  · exact certificate.row_285
  · exact certificate.row_286
  · exact certificate.row_287
  · exact certificate.row_288
  · exact certificate.row_289
  · exact certificate.row_290
  · exact certificate.row_291
  · exact certificate.row_292
  · exact certificate.row_293
  · exact certificate.row_294
  · exact certificate.row_295
  · exact certificate.row_296
  · exact certificate.row_297
  · exact certificate.row_298
  · exact certificate.row_299
  · exact certificate.row_300
  · exact certificate.row_301
  · exact certificate.row_302
  · exact certificate.row_303
  · exact certificate.row_304
  · exact certificate.row_305
  · exact certificate.row_306
  · exact certificate.row_307
  · exact certificate.row_308
  · exact certificate.row_309
  · exact certificate.row_310
  · exact certificate.row_311
  · exact certificate.row_312
  · exact certificate.row_313
  · exact certificate.row_314
  · exact certificate.row_315
  · exact certificate.row_316
  · exact certificate.row_317
  · exact certificate.row_318
  · exact certificate.row_319

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 320 row_count 64

theorem chunk_5 (i : Fin 64) (hi : 320+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (320+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(320+i.val) := by
  fin_cases i
  · exact certificate.row_320
  · exact certificate.row_321
  · exact certificate.row_322
  · exact certificate.row_323
  · exact certificate.row_324
  · exact certificate.row_325
  · exact certificate.row_326
  · exact certificate.row_327
  · exact certificate.row_328
  · exact certificate.row_329
  · exact certificate.row_330
  · exact certificate.row_331
  · exact certificate.row_332
  · exact certificate.row_333
  · exact certificate.row_334
  · exact certificate.row_335
  · exact certificate.row_336
  · exact certificate.row_337
  · exact certificate.row_338
  · exact certificate.row_339
  · exact certificate.row_340
  · exact certificate.row_341
  · exact certificate.row_342
  · exact certificate.row_343
  · exact certificate.row_344
  · exact certificate.row_345
  · exact certificate.row_346
  · exact certificate.row_347
  · exact certificate.row_348
  · exact certificate.row_349
  · exact certificate.row_350
  · exact certificate.row_351
  · exact certificate.row_352
  · exact certificate.row_353
  · exact certificate.row_354
  · exact certificate.row_355
  · exact certificate.row_356
  · exact certificate.row_357
  · exact certificate.row_358
  · exact certificate.row_359
  · exact certificate.row_360
  · exact certificate.row_361
  · exact certificate.row_362
  · exact certificate.row_363
  · exact certificate.row_364
  · exact certificate.row_365
  · exact certificate.row_366
  · exact certificate.row_367
  · exact certificate.row_368
  · exact certificate.row_369
  · exact certificate.row_370
  · exact certificate.row_371
  · exact certificate.row_372
  · exact certificate.row_373
  · exact certificate.row_374
  · exact certificate.row_375
  · exact certificate.row_376
  · exact certificate.row_377
  · exact certificate.row_378
  · exact certificate.row_379
  · exact certificate.row_380
  · exact certificate.row_381
  · exact certificate.row_382
  · exact certificate.row_383

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 384 row_count 64

theorem chunk_6 (i : Fin 64) (hi : 384+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (384+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(384+i.val) := by
  fin_cases i
  · exact certificate.row_384
  · exact certificate.row_385
  · exact certificate.row_386
  · exact certificate.row_387
  · exact certificate.row_388
  · exact certificate.row_389
  · exact certificate.row_390
  · exact certificate.row_391
  · exact certificate.row_392
  · exact certificate.row_393
  · exact certificate.row_394
  · exact certificate.row_395
  · exact certificate.row_396
  · exact certificate.row_397
  · exact certificate.row_398
  · exact certificate.row_399
  · exact certificate.row_400
  · exact certificate.row_401
  · exact certificate.row_402
  · exact certificate.row_403
  · exact certificate.row_404
  · exact certificate.row_405
  · exact certificate.row_406
  · exact certificate.row_407
  · exact certificate.row_408
  · exact certificate.row_409
  · exact certificate.row_410
  · exact certificate.row_411
  · exact certificate.row_412
  · exact certificate.row_413
  · exact certificate.row_414
  · exact certificate.row_415
  · exact certificate.row_416
  · exact certificate.row_417
  · exact certificate.row_418
  · exact certificate.row_419
  · exact certificate.row_420
  · exact certificate.row_421
  · exact certificate.row_422
  · exact certificate.row_423
  · exact certificate.row_424
  · exact certificate.row_425
  · exact certificate.row_426
  · exact certificate.row_427
  · exact certificate.row_428
  · exact certificate.row_429
  · exact certificate.row_430
  · exact certificate.row_431
  · exact certificate.row_432
  · exact certificate.row_433
  · exact certificate.row_434
  · exact certificate.row_435
  · exact certificate.row_436
  · exact certificate.row_437
  · exact certificate.row_438
  · exact certificate.row_439
  · exact certificate.row_440
  · exact certificate.row_441
  · exact certificate.row_442
  · exact certificate.row_443
  · exact certificate.row_444
  · exact certificate.row_445
  · exact certificate.row_446
  · exact certificate.row_447

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 448 row_count 64

theorem chunk_7 (i : Fin 64) (hi : 448+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (448+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(448+i.val) := by
  fin_cases i
  · exact certificate.row_448
  · exact certificate.row_449
  · exact certificate.row_450
  · exact certificate.row_451
  · exact certificate.row_452
  · exact certificate.row_453
  · exact certificate.row_454
  · exact certificate.row_455
  · exact certificate.row_456
  · exact certificate.row_457
  · exact certificate.row_458
  · exact certificate.row_459
  · exact certificate.row_460
  · exact certificate.row_461
  · exact certificate.row_462
  · exact certificate.row_463
  · exact certificate.row_464
  · exact certificate.row_465
  · exact certificate.row_466
  · exact certificate.row_467
  · exact certificate.row_468
  · exact certificate.row_469
  · exact certificate.row_470
  · exact certificate.row_471
  · exact certificate.row_472
  · exact certificate.row_473
  · exact certificate.row_474
  · exact certificate.row_475
  · exact certificate.row_476
  · exact certificate.row_477
  · exact certificate.row_478
  · exact certificate.row_479
  · exact certificate.row_480
  · exact certificate.row_481
  · exact certificate.row_482
  · exact certificate.row_483
  · exact certificate.row_484
  · exact certificate.row_485
  · exact certificate.row_486
  · exact certificate.row_487
  · exact certificate.row_488
  · exact certificate.row_489
  · exact certificate.row_490
  · exact certificate.row_491
  · exact certificate.row_492
  · exact certificate.row_493
  · exact certificate.row_494
  · exact certificate.row_495
  · exact certificate.row_496
  · exact certificate.row_497
  · exact certificate.row_498
  · exact certificate.row_499
  · exact certificate.row_500
  · exact certificate.row_501
  · exact certificate.row_502
  · exact certificate.row_503
  · exact certificate.row_504
  · exact certificate.row_505
  · exact certificate.row_506
  · exact certificate.row_507
  · exact certificate.row_508
  · exact certificate.row_509
  · exact certificate.row_510
  · exact certificate.row_511

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 512 row_count 64

theorem chunk_8 (i : Fin 64) (hi : 512+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (512+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(512+i.val) := by
  fin_cases i
  · exact certificate.row_512
  · exact certificate.row_513
  · exact certificate.row_514
  · exact certificate.row_515
  · exact certificate.row_516
  · exact certificate.row_517
  · exact certificate.row_518
  · exact certificate.row_519
  · exact certificate.row_520
  · exact certificate.row_521
  · exact certificate.row_522
  · exact certificate.row_523
  · exact certificate.row_524
  · exact certificate.row_525
  · exact certificate.row_526
  · exact certificate.row_527
  · exact certificate.row_528
  · exact certificate.row_529
  · exact certificate.row_530
  · exact certificate.row_531
  · exact certificate.row_532
  · exact certificate.row_533
  · exact certificate.row_534
  · exact certificate.row_535
  · exact certificate.row_536
  · exact certificate.row_537
  · exact certificate.row_538
  · exact certificate.row_539
  · exact certificate.row_540
  · exact certificate.row_541
  · exact certificate.row_542
  · exact certificate.row_543
  · exact certificate.row_544
  · exact certificate.row_545
  · exact certificate.row_546
  · exact certificate.row_547
  · exact certificate.row_548
  · exact certificate.row_549
  · exact certificate.row_550
  · exact certificate.row_551
  · exact certificate.row_552
  · exact certificate.row_553
  · exact certificate.row_554
  · exact certificate.row_555
  · exact certificate.row_556
  · exact certificate.row_557
  · exact certificate.row_558
  · exact certificate.row_559
  · exact certificate.row_560
  · exact certificate.row_561
  · exact certificate.row_562
  · exact certificate.row_563
  · exact certificate.row_564
  · exact certificate.row_565
  · exact certificate.row_566
  · exact certificate.row_567
  · exact certificate.row_568
  · exact certificate.row_569
  · exact certificate.row_570
  · exact certificate.row_571
  · exact certificate.row_572
  · exact certificate.row_573
  · exact certificate.row_574
  · exact certificate.row_575

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 576 row_count 64

theorem chunk_9 (i : Fin 64) (hi : 576+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (576+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(576+i.val) := by
  fin_cases i
  · exact certificate.row_576
  · exact certificate.row_577
  · exact certificate.row_578
  · exact certificate.row_579
  · exact certificate.row_580
  · exact certificate.row_581
  · exact certificate.row_582
  · exact certificate.row_583
  · exact certificate.row_584
  · exact certificate.row_585
  · exact certificate.row_586
  · exact certificate.row_587
  · exact certificate.row_588
  · exact certificate.row_589
  · exact certificate.row_590
  · exact certificate.row_591
  · exact certificate.row_592
  · exact certificate.row_593
  · exact certificate.row_594
  · exact certificate.row_595
  · exact certificate.row_596
  · exact certificate.row_597
  · exact certificate.row_598
  · exact certificate.row_599
  · exact certificate.row_600
  · exact certificate.row_601
  · exact certificate.row_602
  · exact certificate.row_603
  · exact certificate.row_604
  · exact certificate.row_605
  · exact certificate.row_606
  · exact certificate.row_607
  · exact certificate.row_608
  · exact certificate.row_609
  · exact certificate.row_610
  · exact certificate.row_611
  · exact certificate.row_612
  · exact certificate.row_613
  · exact certificate.row_614
  · exact certificate.row_615
  · exact certificate.row_616
  · exact certificate.row_617
  · exact certificate.row_618
  · exact certificate.row_619
  · exact certificate.row_620
  · exact certificate.row_621
  · exact certificate.row_622
  · exact certificate.row_623
  · exact certificate.row_624
  · exact certificate.row_625
  · exact certificate.row_626
  · exact certificate.row_627
  · exact certificate.row_628
  · exact certificate.row_629
  · exact certificate.row_630
  · exact certificate.row_631
  · exact certificate.row_632
  · exact certificate.row_633
  · exact certificate.row_634
  · exact certificate.row_635
  · exact certificate.row_636
  · exact certificate.row_637
  · exact certificate.row_638
  · exact certificate.row_639

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 640 row_count 64

theorem chunk_10 (i : Fin 64) (hi : 640+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (640+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(640+i.val) := by
  fin_cases i
  · exact certificate.row_640
  · exact certificate.row_641
  · exact certificate.row_642
  · exact certificate.row_643
  · exact certificate.row_644
  · exact certificate.row_645
  · exact certificate.row_646
  · exact certificate.row_647
  · exact certificate.row_648
  · exact certificate.row_649
  · exact certificate.row_650
  · exact certificate.row_651
  · exact certificate.row_652
  · exact certificate.row_653
  · exact certificate.row_654
  · exact certificate.row_655
  · exact certificate.row_656
  · exact certificate.row_657
  · exact certificate.row_658
  · exact certificate.row_659
  · exact certificate.row_660
  · exact certificate.row_661
  · exact certificate.row_662
  · exact certificate.row_663
  · exact certificate.row_664
  · exact certificate.row_665
  · exact certificate.row_666
  · exact certificate.row_667
  · exact certificate.row_668
  · exact certificate.row_669
  · exact certificate.row_670
  · exact certificate.row_671
  · exact certificate.row_672
  · exact certificate.row_673
  · exact certificate.row_674
  · exact certificate.row_675
  · exact certificate.row_676
  · exact certificate.row_677
  · exact certificate.row_678
  · exact certificate.row_679
  · exact certificate.row_680
  · exact certificate.row_681
  · exact certificate.row_682
  · exact certificate.row_683
  · exact certificate.row_684
  · exact certificate.row_685
  · exact certificate.row_686
  · exact certificate.row_687
  · exact certificate.row_688
  · exact certificate.row_689
  · exact certificate.row_690
  · exact certificate.row_691
  · exact certificate.row_692
  · exact certificate.row_693
  · exact certificate.row_694
  · exact certificate.row_695
  · exact certificate.row_696
  · exact certificate.row_697
  · exact certificate.row_698
  · exact certificate.row_699
  · exact certificate.row_700
  · exact certificate.row_701
  · exact certificate.row_702
  · exact certificate.row_703

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 704 row_count 64

theorem chunk_11 (i : Fin 64) (hi : 704+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (704+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(704+i.val) := by
  fin_cases i
  · exact certificate.row_704
  · exact certificate.row_705
  · exact certificate.row_706
  · exact certificate.row_707
  · exact certificate.row_708
  · exact certificate.row_709
  · exact certificate.row_710
  · exact certificate.row_711
  · exact certificate.row_712
  · exact certificate.row_713
  · exact certificate.row_714
  · exact certificate.row_715
  · exact certificate.row_716
  · exact certificate.row_717
  · exact certificate.row_718
  · exact certificate.row_719
  · exact certificate.row_720
  · exact certificate.row_721
  · exact certificate.row_722
  · exact certificate.row_723
  · exact certificate.row_724
  · exact certificate.row_725
  · exact certificate.row_726
  · exact certificate.row_727
  · exact certificate.row_728
  · exact certificate.row_729
  · exact certificate.row_730
  · exact certificate.row_731
  · exact certificate.row_732
  · exact certificate.row_733
  · exact certificate.row_734
  · exact certificate.row_735
  · exact certificate.row_736
  · exact certificate.row_737
  · exact certificate.row_738
  · exact certificate.row_739
  · exact certificate.row_740
  · exact certificate.row_741
  · exact certificate.row_742
  · exact certificate.row_743
  · exact certificate.row_744
  · exact certificate.row_745
  · exact certificate.row_746
  · exact certificate.row_747
  · exact certificate.row_748
  · exact certificate.row_749
  · exact certificate.row_750
  · exact certificate.row_751
  · exact certificate.row_752
  · exact certificate.row_753
  · exact certificate.row_754
  · exact certificate.row_755
  · exact certificate.row_756
  · exact certificate.row_757
  · exact certificate.row_758
  · exact certificate.row_759
  · exact certificate.row_760
  · exact certificate.row_761
  · exact certificate.row_762
  · exact certificate.row_763
  · exact certificate.row_764
  · exact certificate.row_765
  · exact certificate.row_766
  · exact certificate.row_767

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 768 row_count 64

theorem chunk_12 (i : Fin 64) (hi : 768+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (768+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(768+i.val) := by
  fin_cases i
  · exact certificate.row_768
  · exact certificate.row_769
  · exact certificate.row_770
  · exact certificate.row_771
  · exact certificate.row_772
  · exact certificate.row_773
  · exact certificate.row_774
  · exact certificate.row_775
  · exact certificate.row_776
  · exact certificate.row_777
  · exact certificate.row_778
  · exact certificate.row_779
  · exact certificate.row_780
  · exact certificate.row_781
  · exact certificate.row_782
  · exact certificate.row_783
  · exact certificate.row_784
  · exact certificate.row_785
  · exact certificate.row_786
  · exact certificate.row_787
  · exact certificate.row_788
  · exact certificate.row_789
  · exact certificate.row_790
  · exact certificate.row_791
  · exact certificate.row_792
  · exact certificate.row_793
  · exact certificate.row_794
  · exact certificate.row_795
  · exact certificate.row_796
  · exact certificate.row_797
  · exact certificate.row_798
  · exact certificate.row_799
  · exact certificate.row_800
  · exact certificate.row_801
  · exact certificate.row_802
  · exact certificate.row_803
  · exact certificate.row_804
  · exact certificate.row_805
  · exact certificate.row_806
  · exact certificate.row_807
  · exact certificate.row_808
  · exact certificate.row_809
  · exact certificate.row_810
  · exact certificate.row_811
  · exact certificate.row_812
  · exact certificate.row_813
  · exact certificate.row_814
  · exact certificate.row_815
  · exact certificate.row_816
  · exact certificate.row_817
  · exact certificate.row_818
  · exact certificate.row_819
  · exact certificate.row_820
  · exact certificate.row_821
  · exact certificate.row_822
  · exact certificate.row_823
  · exact certificate.row_824
  · exact certificate.row_825
  · exact certificate.row_826
  · exact certificate.row_827
  · exact certificate.row_828
  · exact certificate.row_829
  · exact certificate.row_830
  · exact certificate.row_831

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 832 row_count 64

theorem chunk_13 (i : Fin 64) (hi : 832+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (832+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(832+i.val) := by
  fin_cases i
  · exact certificate.row_832
  · exact certificate.row_833
  · exact certificate.row_834
  · exact certificate.row_835
  · exact certificate.row_836
  · exact certificate.row_837
  · exact certificate.row_838
  · exact certificate.row_839
  · exact certificate.row_840
  · exact certificate.row_841
  · exact certificate.row_842
  · exact certificate.row_843
  · exact certificate.row_844
  · exact certificate.row_845
  · exact certificate.row_846
  · exact certificate.row_847
  · exact certificate.row_848
  · exact certificate.row_849
  · exact certificate.row_850
  · exact certificate.row_851
  · exact certificate.row_852
  · exact certificate.row_853
  · exact certificate.row_854
  · exact certificate.row_855
  · exact certificate.row_856
  · exact certificate.row_857
  · exact certificate.row_858
  · exact certificate.row_859
  · exact certificate.row_860
  · exact certificate.row_861
  · exact certificate.row_862
  · exact certificate.row_863
  · exact certificate.row_864
  · exact certificate.row_865
  · exact certificate.row_866
  · exact certificate.row_867
  · exact certificate.row_868
  · exact certificate.row_869
  · exact certificate.row_870
  · exact certificate.row_871
  · exact certificate.row_872
  · exact certificate.row_873
  · exact certificate.row_874
  · exact certificate.row_875
  · exact certificate.row_876
  · exact certificate.row_877
  · exact certificate.row_878
  · exact certificate.row_879
  · exact certificate.row_880
  · exact certificate.row_881
  · exact certificate.row_882
  · exact certificate.row_883
  · exact certificate.row_884
  · exact certificate.row_885
  · exact certificate.row_886
  · exact certificate.row_887
  · exact certificate.row_888
  · exact certificate.row_889
  · exact certificate.row_890
  · exact certificate.row_891
  · exact certificate.row_892
  · exact certificate.row_893
  · exact certificate.row_894
  · exact certificate.row_895

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 896 row_count 64

theorem chunk_14 (i : Fin 64) (hi : 896+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (896+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(896+i.val) := by
  fin_cases i
  · exact certificate.row_896
  · exact certificate.row_897
  · exact certificate.row_898
  · exact certificate.row_899
  · exact certificate.row_900
  · exact certificate.row_901
  · exact certificate.row_902
  · exact certificate.row_903
  · exact certificate.row_904
  · exact certificate.row_905
  · exact certificate.row_906
  · exact certificate.row_907
  · exact certificate.row_908
  · exact certificate.row_909
  · exact certificate.row_910
  · exact certificate.row_911
  · exact certificate.row_912
  · exact certificate.row_913
  · exact certificate.row_914
  · exact certificate.row_915
  · exact certificate.row_916
  · exact certificate.row_917
  · exact certificate.row_918
  · exact certificate.row_919
  · exact certificate.row_920
  · exact certificate.row_921
  · exact certificate.row_922
  · exact certificate.row_923
  · exact certificate.row_924
  · exact certificate.row_925
  · exact certificate.row_926
  · exact certificate.row_927
  · exact certificate.row_928
  · exact certificate.row_929
  · exact certificate.row_930
  · exact certificate.row_931
  · exact certificate.row_932
  · exact certificate.row_933
  · exact certificate.row_934
  · exact certificate.row_935
  · exact certificate.row_936
  · exact certificate.row_937
  · exact certificate.row_938
  · exact certificate.row_939
  · exact certificate.row_940
  · exact certificate.row_941
  · exact certificate.row_942
  · exact certificate.row_943
  · exact certificate.row_944
  · exact certificate.row_945
  · exact certificate.row_946
  · exact certificate.row_947
  · exact certificate.row_948
  · exact certificate.row_949
  · exact certificate.row_950
  · exact certificate.row_951
  · exact certificate.row_952
  · exact certificate.row_953
  · exact certificate.row_954
  · exact certificate.row_955
  · exact certificate.row_956
  · exact certificate.row_957
  · exact certificate.row_958
  · exact certificate.row_959

certify_sparse_rows certificate from "certificates/finite/n24/sparse.bin" inverse_file "certificates/finite/n24/inverse.bin" inverse_fn Quartic.FiniteEndpointInverse24.binaryInverse row_fn Quartic.FiniteEndpointMetadata24Data.naturalRow nwords 275 start_index 960 row_count 64

theorem chunk_15 (i : Fin 64) (hi : 960+i.val < 17550) :
    xorSum ((FiniteEndpointMetadata24Data.naturalRow (960+i.val)).map
      FiniteEndpointInverse24.binaryInverse) = 2^(960+i.val) := by
  fin_cases i
  · exact certificate.row_960
  · exact certificate.row_961
  · exact certificate.row_962
  · exact certificate.row_963
  · exact certificate.row_964
  · exact certificate.row_965
  · exact certificate.row_966
  · exact certificate.row_967
  · exact certificate.row_968
  · exact certificate.row_969
  · exact certificate.row_970
  · exact certificate.row_971
  · exact certificate.row_972
  · exact certificate.row_973
  · exact certificate.row_974
  · exact certificate.row_975
  · exact certificate.row_976
  · exact certificate.row_977
  · exact certificate.row_978
  · exact certificate.row_979
  · exact certificate.row_980
  · exact certificate.row_981
  · exact certificate.row_982
  · exact certificate.row_983
  · exact certificate.row_984
  · exact certificate.row_985
  · exact certificate.row_986
  · exact certificate.row_987
  · exact certificate.row_988
  · exact certificate.row_989
  · exact certificate.row_990
  · exact certificate.row_991
  · exact certificate.row_992
  · exact certificate.row_993
  · exact certificate.row_994
  · exact certificate.row_995
  · exact certificate.row_996
  · exact certificate.row_997
  · exact certificate.row_998
  · exact certificate.row_999
  · exact certificate.row_1000
  · exact certificate.row_1001
  · exact certificate.row_1002
  · exact certificate.row_1003
  · exact certificate.row_1004
  · exact certificate.row_1005
  · exact certificate.row_1006
  · exact certificate.row_1007
  · exact certificate.row_1008
  · exact certificate.row_1009
  · exact certificate.row_1010
  · exact certificate.row_1011
  · exact certificate.row_1012
  · exact certificate.row_1013
  · exact certificate.row_1014
  · exact certificate.row_1015
  · exact certificate.row_1016
  · exact certificate.row_1017
  · exact certificate.row_1018
  · exact certificate.row_1019
  · exact certificate.row_1020
  · exact certificate.row_1021
  · exact certificate.row_1022
  · exact certificate.row_1023

end Quartic.FiniteEndpointRows24
