module

public import Mathlib.RingTheory.MvPolynomial.Homogeneous
public import Mathlib.RingTheory.MvPolynomial.Basic
public import Mathlib.Data.Finsupp.Multiset
public import Mathlib.Data.Sym.Card
public import Mathlib.LinearAlgebra.Dimension.Constructions
public import Mathlib.LinearAlgebra.Dimension.Finrank
public import Mathlib.RingTheory.Ideal.Quotient.Operations
public import Mathlib.RingTheory.PowerSeries.WellKnown

@[expose] public section

/-! An independent statement of the manuscript's conclusion. This module
imports only Mathlib and describes the actual homogeneous pieces of the
polynomial quotient and the positively truncated predicted Hilbert series. -/
noncomputable section
namespace FrobergPaper
open MvPolynomial Module

/-- The polynomial ring in `n` variables over `K`. -/
abbrev Poly (K : Type*) [Field K] (n : ℕ) := MvPolynomial (Fin n) K
/-- The vector space of homogeneous polynomials of total degree `d`. -/
abbrev Forms (K : Type*) [Field K] (n d : ℕ) :=
  MvPolynomial.homogeneousSubmodule (Fin n) K d

/-- Multisets of `d` variables identify the monomials of total degree `d`. -/
def exponentEquiv (n d : ℕ) : Sym (Fin n) d ≃ {e : Fin n →₀ ℕ // e.degree=d} :=
  Sym.equivNatSum (Fin n) d

/-- The usual monomial basis of homogeneous degree `d`. -/
def formsBasis (K : Type*) [Field K] (n d : ℕ) :
    Basis (Sym (Fin n) d) K (Forms K n d) := by
  rw [Forms,MvPolynomial.homogeneousSubmodule_eq_finsupp_supported]
  exact (MvPolynomial.basisRestrictSupport K {e : Fin n →₀ ℕ | e.degree=d}).reindex
    (exponentEquiv n d).symm

/-- One coefficient for each of the `r` generators and degree-`d` monomials. -/
abbrev CoefficientIndex (n d r : ℕ) := Fin r × Sym (Fin n) d

/-- The `i`th homogeneous generator determined by the coefficient tuple `a`. -/
def coefficientForms (K : Type*) [Field K] (n d r : ℕ)
    (a : CoefficientIndex n d r → K) (i : Fin r) : Forms K n d :=
  (formsBasis K n d).equivFun.symm (fun m => a (i,m))

/-- The span of the given ordered tuple of `r` homogeneous generators. -/
def coefficientSpace (K : Type*) [Field K] (n d r : ℕ)
    (a : CoefficientIndex n d r → K) : Submodule K (Poly K n) :=
  Submodule.span K (Set.range (fun i => (coefficientForms K n d r a i).val))

/-- The degree-`j` forms mapped into the actual quotient by the generated ideal. -/
def formToRingQuotient {K : Type*} [Field K] {n : ℕ}
    (j : ℕ) (W : Submodule K (Poly K n)) :
    Forms K n j →ₗ[K] Poly K n ⧸ Ideal.span (W : Set (Poly K n)) :=
  (Ideal.Quotient.mkₐ K (Ideal.span (W : Set (Poly K n)))).toLinearMap.comp
    (Forms K n j).subtype

/-- Dimension of the degree-`j` image in the quotient by the ideal generated by `W`. -/
def hilbertFunction {K : Type*} [Field K] {n : ℕ}
    (W : Submodule K (Poly K n)) (j : ℕ) : ℕ :=
  Module.finrank K (LinearMap.range (formToRingQuotient j W))

/-- The formal power series `(1-t^d)^r/(1-t)^n` over the integers. -/
def predictionSeries (n d r : ℕ) : PowerSeries ℤ :=
  (1-PowerSeries.X^d)^r*(PowerSeries.invOneSubPow ℤ n).val

/-- The integer coefficient of `t^j` in the untruncated predicted series. -/
def predictionCoefficient (n d r j : ℕ) : ℤ :=
  PowerSeries.coeff j (predictionSeries n d r)

/-- Keep coefficients strictly before the first nonpositive coefficient. -/
def positiveTruncation (a : ℕ → ℤ) (j : ℕ) : ℕ := by
  classical
  exact if ∀ i∈Finset.range (j+1),0<a i then (a j).toNat else 0

/-- The degree-`j` value of Fröberg's positively truncated prediction. -/
def predictedHilbertFunction (n d r j : ℕ) : ℕ :=
  positiveTruncation (predictionCoefficient n d r) j

/-- A single nonempty principal open gives all asserted homogeneous dimensions. -/
def GenericHilbertThrough (K : Type*) [Field K] (n d r bound : ℕ) : Prop :=
  ∃ D : MvPolynomial (CoefficientIndex n d r) K,
    (∃ a,eval a D≠0) ∧ ∀ a,eval a D≠0 → ∀ j≤bound,
      hilbertFunction (coefficientSpace K n d r a) j=predictedHilbertFunction n d r j

/-- The threshold depends only on the positive generating degree, uniformly
over all infinite fields and every number of generators. -/
def Statement : Prop :=
  ∀ d : ℕ,1≤d → ∃ N : ℕ,1≤N ∧ ∀ (K : Type) [Field K] [Infinite K],
    ∀ n : ℕ,N≤n → ∀ r : ℕ,GenericHilbertThrough K n d r (2*d)

/-- Theorem 1.1: Fröberg's prediction through degree `2d`, with the variable
threshold independent of the infinite field and number of generators.
This declaration is the registry's statement specification; its proof is
supplied independently in Solution.lean. -/
theorem main_result : Statement := by
  sorry

end FrobergPaper
