module

public import Froberg.OuterFiberAction

@[expose] public section

/-! Actual target-fiber shadows of independent source-fiber subspaces. -/
noncomputable section
namespace Froberg.AttachedMultiplication
open Module Quartic.HomogeneousCoefficientCoordinates
variable {K I : Type*} [Field K] [Fintype I] [DecidableEq I] {n s d h : ℕ}
variable (e : I → Fin n →₀ ℕ) (v : I → Fin h → K) (he : ∀ i, (e i).degree = s)

/-- The target fiber generated by all source-fiber projections. -/
def fiberShadow
    (C : (a : Exponent n s) → Submodule K ((Fin h → K) ⧸ relationFiber e v a.val))
    (b : Exponent n (s+d)) : Submodule K ((Fin h → K) ⧸ relationFiber e v b.val) :=
  ⨆ a : {a : Exponent n s // a.val ≤ b.val},
    (C a.val).map (fiberProjection e v a.property)

/-- Every separate target-shadow vector is an actual polynomial product of an
independent source-fiber vector and a homogeneous monomial. -/
theorem single_shadow_mem_image
    (C : (a : Exponent n s) → Submodule K ((Fin h → K) ⧸ relationFiber e v a.val))
    (b : Exponent n (s+d)) :
    (fiberShadow e v C b).map (LinearMap.single K _ b) ≤
      Quartic.BilinearImage.image (fiberMultiply (d := d) e v he) (Submodule.pi Set.univ C) := by
  classical
  rw [fiberShadow,Submodule.map_iSup]
  apply iSup_le
  intro a
  rw [← Submodule.map_comp]
  rintro y ⟨u,hu,rfl⟩
  have hdeg : (b.val-a.val.val).degree = d := by
    have hh := congrArg Finsupp.degree (add_tsub_cancel_of_le a.property)
    rw [map_add,a.val.property,b.property] at hh
    omega
  let q : Exponent n d := ⟨b.val-a.val.val,hdeg⟩
  have hadd : addExponent a.val q = b := Subtype.ext (add_tsub_cancel_of_le a.property)
  have hmem : Pi.single a.val u ∈ Submodule.pi Set.univ C := by
    apply Submodule.mem_pi.mpr
    intro j _
    by_cases hj : j=a.val
    · subst j
      simpa using hu
    · simpa only [Pi.single_eq_of_ne hj] using (C j).zero_mem
  have hp := Quartic.BilinearImage.product_mem (fiberMultiply (d := d) e v he)
    (Submodule.pi Set.univ C) (monomialForm q) (Pi.single a.val u) hmem
  rw [fiberMultiply_monomial_single] at hp
  let insert : {c : Exponent n (s+d) // a.val.val ≤ c.val} →
      ((c : Exponent n (s+d)) → (Fin h → K) ⧸ relationFiber e v c.val) :=
    fun c => Pi.single c.val (fiberProjection e v c.property u)
  have hext : (⟨addExponent a.val q,le_add_right le_rfl⟩ :
      {c : Exponent n (s+d) // a.val.val ≤ c.val}) = ⟨b,a.property⟩ := Subtype.ext hadd
  have hvec := congrArg insert hext
  change (Pi.single (addExponent a.val q) (fiberProjection e v (le_add_right le_rfl) u) :
    (c : Exponent n (s+d)) → (Fin h → K) ⧸ relationFiber e v c.val) =
      Pi.single b (fiberProjection e v a.property u) at hvec
  rw [hvec] at hp
  exact hp

/-- The direct sum of the target shadows lies in the genuine full product image. -/
theorem pi_shadow_le_image
    (C : (a : Exponent n s) → Submodule K ((Fin h → K) ⧸ relationFiber e v a.val)) :
    Submodule.pi Set.univ (fiberShadow (d := d) e v C) ≤
      Quartic.BilinearImage.image (fiberMultiply (d := d) e v he) (Submodule.pi Set.univ C) := by
  classical
  intro x hx
  rw [← Finset.univ_sum_single x]
  apply Submodule.sum_mem
  intro b _
  exact single_shadow_mem_image e v he C b
    ⟨x b,Submodule.mem_pi.mp hx b (Set.mem_univ b),rfl⟩

private def piSubmoduleEquiv {A : Type*} {V : A → Type*}
    [∀ a, AddCommGroup (V a)] [∀ a, Module K (V a)]
    (C : (a : A) → Submodule K (V a)) :
    (Submodule.pi Set.univ C) ≃ₗ[K] ((a : A) → C a) where
  toFun x a := ⟨x.val a,Submodule.mem_pi.mp x.property a (Set.mem_univ a)⟩
  invFun x := ⟨fun a => (x a).val,Submodule.mem_pi.mpr (fun a _ => (x a).property)⟩
  left_inv _ := Subtype.ext rfl
  right_inv _ := funext (fun _ => Subtype.ext rfl)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Target-fiber dimensions add, giving a lower bound for actual multiplication. -/
theorem sum_shadow_finrank_le_image
    (C : (a : Exponent n s) → Submodule K ((Fin h → K) ⧸ relationFiber e v a.val)) :
    (∑ b, finrank K (fiberShadow (d := d) e v C b)) ≤
      finrank K (Quartic.BilinearImage.image (fiberMultiply (d := d) e v he) (Submodule.pi Set.univ C)) := by
  letI : ∀ b : Exponent n (s+d), Module.Free K (fiberShadow e v C b) := fun _ => inferInstance
  have hh := Submodule.finrank_mono (pi_shadow_le_image (d := d) e v he C)
  rw [(piSubmoduleEquiv (fiberShadow (d := d) e v C)).finrank_eq,
    Module.finrank_pi_fintype] at hh
  exact hh

/-- Each actual quotient projection supplies a lower bound for its target shadow. -/
theorem projection_finrank_le_shadow
    (C : (a : Exponent n s) → Submodule K ((Fin h → K) ⧸ relationFiber e v a.val))
    (a : Exponent n s) (b : Exponent n (s+d)) (hab : a.val ≤ b.val) :
    finrank K ((C a).map (fiberProjection e v hab)) ≤ finrank K (fiberShadow e v C b) :=
  Submodule.finrank_mono (le_iSup (fun a : {a : Exponent n s // a.val ≤ b.val} =>
    (C a.val).map (fiberProjection e v a.property)) ⟨a,hab⟩)

end Froberg.AttachedMultiplication
