import Froberg.Graded

/-!
# Normalized last-row elimination for the prefix incidence charts

A nonzero last row supported on a fixed set can be normalized at one permitted
coordinate. Subtracting its multiples from the other rows lowers the span rank
by exactly one. Consequently the nonzero-last-row strata reduce to ordinary
affine rank charts in one fewer ambient coordinate, avoiding a further tail-rank
stratification.
-/

noncomputable section
namespace Froberg.PrefixCharts
open Module
variable {K ι : Type*} [Field K] [DecidableEq ι]

/-- Eliminate a normalized pivot coordinate using the distinguished row `z`. -/
def deletePivot (z : ι → K) (j : ι) : (ι → K) →ₗ[K] ({k : ι // k ≠ j} → K) where
  toFun x k := x k.val - x j * z k.val
  map_add' x y := by ext k; simp [add_mul]; ring
  map_smul' c x := by ext k; simp; ring

omit [DecidableEq ι] in
@[simp] theorem deletePivot_apply (z : ι → K) (j : ι) (x : ι → K)
    (k : {k : ι // k ≠ j}) : deletePivot z j x k = x k.val - x j * z k.val := rfl

/-- Reconstruct a row from its pivot coefficient and its eliminated remainder.
The expression is polynomial in all three sets of coordinates. -/
def reconstruct (z : ι → K) (j : ι) (c : K) (y : {k : ι // k ≠ j} → K) : ι → K :=
  fun k => if h : k = j then c else y ⟨k, h⟩ + c * z k

@[simp] theorem reconstruct_pivot (z : ι → K) (j : ι) (c : K)
    (y : {k : ι // k ≠ j} → K) : reconstruct z j c y j = c := by simp [reconstruct]

@[simp] theorem deletePivot_reconstruct (z : ι → K) (j : ι) (c : K)
    (y : {k : ι // k ≠ j} → K) : deletePivot z j (reconstruct z j c y) = y := by
  ext k
  simp [deletePivot, reconstruct, k.property]

@[simp] theorem reconstruct_deletePivot (z : ι → K) (j : ι) (x : ι → K) :
    reconstruct z j (x j) (deletePivot z j x) = x := by
  ext k
  by_cases h : k = j
  · subst k; simp
  · simp [reconstruct, h]

omit [DecidableEq ι] in
@[simp] theorem deletePivot_self (z : ι → K) (j : ι) (hz : z j = 1) :
    deletePivot z j z = 0 := by
  ext k
  simp [deletePivot, hz]

/-- The eliminated vector vanishes exactly when the row is a scalar multiple
of the distinguished normalized row. -/
theorem deletePivot_eq_zero_iff (z : ι → K) (j : ι) (hz : z j = 1) (x : ι → K) :
    deletePivot z j x = 0 ↔ x = (x j) • z := by
  constructor
  · intro hx
    ext k
    by_cases h : k = j
    · subst k; simp [hz]
    · have hk := congrFun hx ⟨k, h⟩
      simpa [deletePivot, sub_eq_zero] using hk
  · intro hx
    rw [hx, map_smul, deletePivot_self z j hz, smul_zero]

/-- On any row span containing `z`, the elimination kernel is precisely one
scalar coordinate. -/
def pivotKernelEquiv (z : ι → K) (j : ι) (hz : z j = 1)
    (S : Submodule K (ι → K)) (hzS : z ∈ S) :
    (deletePivot z j).domRestrict S |>.ker ≃ₗ[K] K where
  toFun x := x.val.val j
  invFun c := ⟨⟨c • z, S.smul_mem c hzS⟩, by
    change deletePivot z j (c • z) = 0
    rw [map_smul, deletePivot_self z j hz, smul_zero]⟩
  left_inv x := by
    apply Subtype.ext
    apply Subtype.ext
    exact ((deletePivot_eq_zero_iff z j hz x.val.val).mp x.property).symm
  right_inv c := by simp [hz]
  map_add' x y := rfl
  map_smul' c x := rfl

variable [Fintype ι]

/-- Exact rank drop after eliminating a normalized nonzero row. -/
theorem finrank_deletePivot (z : ι → K) (j : ι) (hz : z j = 1)
    (S : Submodule K (ι → K)) (hzS : z ∈ S) :
    finrank K (S.map (deletePivot z j)) + 1 = finrank K S := by
  have hk : finrank K ((deletePivot z j).domRestrict S).ker = 1 :=
    (pivotKernelEquiv z j hz S hzS).finrank_eq.trans (finrank_self K)
  have h := ((deletePivot z j).domRestrict S).finrank_range_add_finrank_ker
  rw [LinearMap.range_domRestrict, hk] at h
  exact h

/-- The map of the full row span is generated by the eliminated ordinary rows;
the distinguished last row contributes zero. -/
theorem map_rowSpan {q : ℕ} (F : Fin q → ι → K) (z : ι → K) (j : ι) (hz : z j = 1) :
    (Submodule.span K (Set.range F) ⊔ K ∙ z).map (deletePivot z j) =
      Submodule.span K (Set.range (fun i => deletePivot z j (F i))) := by
  rw [Submodule.map_sup, Submodule.map_span, Submodule.map_span]
  simp [← Set.range_comp, Function.comp_def, deletePivot_self z j hz]

/-- Rank of the ordinary rows modulo a nonzero last row is one less than the
full tuple rank, with no genericity condition. -/
theorem finrank_eliminated_rows {q : ℕ} (F : Fin q → ι → K)
    (z : ι → K) (j : ι) (hz : z j = 1) :
    finrank K (Submodule.span K (Set.range (fun i => deletePivot z j (F i)))) + 1 =
      finrank K (Submodule.span K (Set.range F) ⊔ K ∙ z : Submodule K (ι → K)) := by
  have hzS : z ∈ Submodule.span K (Set.range F) ⊔ K ∙ z :=
    (le_sup_right : K ∙ z ≤ _ ) (Submodule.mem_span_singleton_self z)
  have h := finrank_deletePivot z j hz (Submodule.span K (Set.range F) ⊔ K ∙ z) hzS
  rw [map_rowSpan F z j hz] at h
  exact h

/-- A nonzero row with prescribed support can be normalized at one of its
permitted coordinates. This accounts for one fewer projective parameter. -/
theorem exists_normalized_supported_row (T : Finset ι) (z : ι → K) (hz : z ≠ 0)
    (hsupport : ∀ j, j ∉ T → z j = 0) :
    ∃ j ∈ T, ∃ c : K, c ≠ 0 ∧ ∃ z' : ι → K,
      z' j = 1 ∧ (∀ k, k ∉ T → z' k = 0) ∧ z = c • z' := by
  obtain ⟨j, hj⟩ : ∃ j, z j ≠ 0 := by
    by_contra! h
    exact hz (funext h)
  have hjT : j ∈ T := by
    by_contra hjT
    exact hj (hsupport j hjT)
  refine ⟨j, hjT, z j, hj, (z j)⁻¹ • z, ?_, ?_, ?_⟩
  · simp [hj]
  · intro k hk
    simp [hsupport k hk]
  · ext k
    simp [hj]

/-- Parameter count for the nonzero-last-row chart: the normalized permitted
row, one scalar for each ordinary row, and an affine rank-`k-1` chart in the
remaining `N-1` coordinates. -/
theorem nonzero_last_row_parameter_count {N q s k : ℕ}
    (hs : 0 < s) (hk : 0 < k) (hkN : k ≤ N) :
    (s - 1) + q + (k - 1) * ((N - 1) - (k - 1)) + q * (k - 1) =
      q * k + (k - 1) * (N - k) + s - 1 := by
  have hNk : (N - 1) - (k - 1) = N - k := by omega
  rw [hNk]
  have hk' : k - 1 + 1 = k := by omega
  have hs' : s - 1 + 1 = s := by omega
  have hq : q + q * (k - 1) = q * k := by nlinarith
  omega

end Froberg.PrefixCharts
