import Froberg.Graded
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.Isomorphisms

/-!
# Homogeneous pieces of the actual quotient ring

Generalizes the earlier Quartic/QuotientModel construction to arbitrary degrees.
The endpoint quotient used by the homology calculations is identified with the
homogeneous image in the ring quotient, not merely a numerical surrogate.
-/
noncomputable section
namespace Froberg
open MvPolynomial
variable {K : Type*} [Field K] {n d : ℕ}

/-- Projection of a product with a homogeneous form has the expected degree. -/
theorem homogeneousComponent_mul_form (e : ℕ) (f p : Poly K n)
    (hf : f.IsHomogeneous d) :
    homogeneousComponent (d + e) (f * p) = f * homogeneousComponent e p := by
  induction p using MvPolynomial.induction_on' with
  | monomial a c =>
      have ha : (monomial a c : Poly K n).IsHomogeneous a.degree :=
        isHomogeneous_monomial c rfl
      rw [homogeneousComponent_of_mem (hf.mul ha), homogeneousComponent_of_mem ha]
      by_cases h : a.degree = e
      · simp [h]
      · simp [Ne.symm h]
  | add p q hp hq => simp only [mul_add, map_add, hp, hq]

/-- Every homogeneous part of a generated ideal is represented by homogeneous multipliers. -/
theorem homogeneousComponent_mem_products (e : ℕ) (W : Submodule K (Poly K n))
    (hW : W ≤ Forms K n d) {p : Poly K n}
    (hp : p ∈ Ideal.span (W : Set (Poly K n))) :
    homogeneousComponent (d + e) p ∈ W * Forms K n e := by
  have hall : ∀ a : Poly K n, homogeneousComponent (d + e) (a * p) ∈ W * Forms K n e := by
    induction hp using Submodule.span_induction with
    | mem f hf =>
        intro a
        rw [mul_comm a f, homogeneousComponent_mul_form e f a (hW hf)]
        exact Submodule.mul_mem_mul hf (homogeneousComponent_mem e a)
    | zero => intro a; simp
    | add p q hp hq ihp ihq =>
        intro a
        rw [mul_add, map_add]
        exact (W * Forms K n e).add_mem (ihp a) (ihq a)
    | smul b p hp ih =>
        intro a
        change homogeneousComponent (d + e) (a * (b * p)) ∈ W * Forms K n e
        rw [← mul_assoc]
        exact ih (a * b)
  simpa using hall 1

/-- For a homogeneous target, generated-ideal membership is exactly product membership. -/
theorem form_mem_ideal_iff (e : ℕ) (W : Submodule K (Poly K n))
    (hW : W ≤ Forms K n d) (p : Forms K n (d + e)) :
    p.val ∈ Ideal.span (W : Set (Poly K n)) ↔ p.val ∈ W * Forms K n e := by
  constructor
  · intro hp
    have h := homogeneousComponent_mem_products e W hW hp
    rwa [homogeneousComponent_eq_self p.property] at h
  · intro hp
    refine Submodule.mul_induction_on hp ?_ ?_
    · intro f hf a ha
      exact Ideal.mul_mem_right _ _ (Ideal.subset_span hf)
    · intro f g hf hg
      exact Ideal.add_mem _ hf hg

/-- The homogeneous image in the actual quotient ring. -/
def formToRingQuotient (j : ℕ) (W : Submodule K (Poly K n)) :
    Forms K n j →ₗ[K] Poly K n ⧸ Ideal.span (W : Set (Poly K n)) :=
  (Ideal.Quotient.mkₐ K (Ideal.span (W : Set (Poly K n)))).toLinearMap.comp
    (Forms K n j).subtype

/-- Hilbert function of the ideal generated by the given homogeneous subspace. -/
def hilbertFunction (W : Submodule K (Poly K n)) (j : ℕ) : ℕ :=
  Module.finrank K (LinearMap.range (formToRingQuotient j W))

theorem ker_endpointToRingQuotient (W : Submodule K (Poly K n))
    (hW : W ≤ Forms K n d) :
    LinearMap.ker (formToRingQuotient (2 * d) W) = endpointProducts K n d W := by
  ext p
  change Ideal.Quotient.mk (Ideal.span (W : Set (Poly K n))) p.val = 0 ↔
    p.val ∈ W * Forms K n d
  rw [Ideal.Quotient.eq_zero_iff_mem]
  have hp : p.val ∈ Forms K n (d + d) := by simpa only [two_mul] using p.property
  exact form_mem_ideal_iff d W hW ⟨p.val, hp⟩

/-- The actual quotient-ring endpoint agrees with the product-space quotient. -/
def endpointQuotientEquivImage (W : Submodule K (Poly K n))
    (hW : W ≤ Forms K n d) :
    EndpointQuotient K n d W ≃ₗ[K] LinearMap.range (formToRingQuotient (2 * d) W) :=
  (Submodule.quotEquivOfEq _ _ (ker_endpointToRingQuotient W hW).symm).trans
    (formToRingQuotient (2 * d) W).quotKerEquivRange

theorem endpointQuotientEquivImage_mk (W : Submodule K (Poly K n))
    (hW : W ≤ Forms K n d) (p : Forms K n (2 * d)) :
    (endpointQuotientEquivImage W hW (Submodule.Quotient.mk p) :
      Poly K n ⧸ Ideal.span (W : Set (Poly K n))) =
      Ideal.Quotient.mk (Ideal.span (W : Set (Poly K n))) p.val := rfl

theorem endpoint_finrank_eq_hilbertFunction (W : Submodule K (Poly K n))
    (hW : W ≤ Forms K n d) :
    Module.finrank K (EndpointQuotient K n d W) = hilbertFunction W (2 * d) :=
  (endpointQuotientEquivImage W hW).finrank_eq

/-- An ideal generated in degree `d` has no components in smaller degrees. -/
theorem homogeneousComponent_mul_eq_zero_of_lt (j : ℕ) (hj : j < d)
    (f p : Poly K n) (hf : f.IsHomogeneous d) :
    homogeneousComponent j (f * p) = 0 := by
  induction p using MvPolynomial.induction_on' with
  | monomial a c =>
      have ha : (monomial a c : Poly K n).IsHomogeneous a.degree :=
        isHomogeneous_monomial c rfl
      rw [homogeneousComponent_of_mem (hf.mul ha)]
      simp [show j ≠ d + a.degree by omega]
  | add p q hp hq => simp only [mul_add, map_add, hp, hq, add_zero]

theorem homogeneousComponent_ideal_eq_zero (j : ℕ) (hj : j < d)
    (W : Submodule K (Poly K n)) (hW : W ≤ Forms K n d) {p : Poly K n}
    (hp : p ∈ Ideal.span (W : Set (Poly K n))) : homogeneousComponent j p = 0 := by
  have hall : ∀ a : Poly K n, homogeneousComponent j (a * p) = 0 := by
    induction hp using Submodule.span_induction with
    | mem f hf =>
        intro a
        rw [mul_comm]
        exact homogeneousComponent_mul_eq_zero_of_lt j hj f a (hW hf)
    | zero => intro a; simp
    | add p q hp hq ihp ihq => intro a; simp [mul_add, ihp, ihq]
    | smul b p hp ih => intro a; exact (mul_assoc a b p).symm ▸ ih (a * b)
  simpa using hall 1

/-- Below the generating degree, the quotient map is injective. -/
theorem formToRingQuotient_injective_of_lt (j : ℕ) (hj : j < d)
    (W : Submodule K (Poly K n)) (hW : W ≤ Forms K n d) :
    Function.Injective (formToRingQuotient j W) := by
  apply (injective_iff_map_eq_zero _).mpr
  intro p hp
  have hpI : p.val ∈ Ideal.span (W : Set (Poly K n)) := by
    exact Ideal.Quotient.eq_zero_iff_mem.mp hp
  have hz := homogeneousComponent_ideal_eq_zero j hj W hW hpI
  rw [homogeneousComponent_eq_self p.property] at hz
  exact Subtype.ext hz

theorem hilbertFunction_below_degree (hn : 0 < n) (j : ℕ) (hj : j < d)
    (W : Submodule K (Poly K n)) (hW : W ≤ Forms K n d) :
    hilbertFunction W j = (n + j - 1).choose j :=
  (LinearMap.finrank_range_of_inj (formToRingQuotient_injective_of_lt j hj W hW)).trans
    (finrank_forms K n j hn)

/-- Containing every degree-`d` form makes the quotient vanish in all later degrees. -/
theorem formToRingQuotient_eq_zero_of_forms_le (j : ℕ) (hj : d ≤ j)
    (W : Submodule K (Poly K n)) (hW : Forms K n d ≤ W) :
    formToRingQuotient j W = 0 := by
  ext p
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  change p.val ∈ Ideal.span (W : Set (Poly K n))
  have hp : p.val ∈ Forms K n d * Forms K n (j - d) := by
    rw [forms_mul_forms, Nat.add_sub_of_le hj]
    exact p.property
  refine Submodule.mul_induction_on hp ?_ ?_
  · intro f hf a ha
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span (hW hf))
  · intro f g hf hg
    exact Ideal.add_mem _ hf hg

theorem hilbertFunction_zero_of_forms_le (j : ℕ) (hj : d ≤ j)
    (W : Submodule K (Poly K n)) (hW : Forms K n d ≤ W) :
    hilbertFunction W j = 0 := by
  simp [hilbertFunction, formToRingQuotient_eq_zero_of_forms_le j hj W hW]

end Froberg
