import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
import Mathlib.RingTheory.IntegralClosure.Algebra.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.FiniteType

/-!
Finite-module bounds for component function fields.
All rings have the same universe to keep cardinal statements free of lifts.
The slice hypothesis is module finiteness over the subalgebra generated by
the specified elements, not a surjective polynomial parametrization.
-/
noncomputable section
universe u
namespace Quartic.AlgebraicDomainDimension
open Cardinal Algebra
variable {K R A : Type u} [Field K] [CommRing R] [CommRing A]
  [Algebra K R] [Algebra K A] {s : ℕ}

/-- Integrality survives a surjective map, over the image of the specified
slice algebra. This is proved by mapping the monic integral equation. -/
theorem integral_over_image_adjoin (x : Fin s → R)
    [Module.Finite (Algebra.adjoin K (Set.range x)) R]
    (f : R →ₐ[K] A) (hf : Function.Surjective f) :
    Algebra.IsIntegral (Algebra.adjoin K (Set.range (fun i => f (x i)))) A := by
  let S := Algebra.adjoin K (Set.range x)
  let T := Algebra.adjoin K (Set.range (fun i => f (x i)))
  have hmap : S.map f = T := by
    rw [AlgHom.map_adjoin, ← Set.range_comp]
    rfl
  let φ : S →ₐ[K] T := (f.comp S.val).codRestrict T (by
    intro a
    rw [← hmap]
    exact ⟨a.val,a.property,rfl⟩)
  refine ⟨fun a => ?_⟩
  obtain ⟨r,rfl⟩ := hf a
  exact IsIntegral.map_of_comp_eq φ.toRingHom f.toRingHom
    (by ext a; rfl) (IsIntegral.of_finite S r)

/-- Every domain quotient of an algebra finite over `s` slice elements has
transcendence degree at most `s`. No dimension hypothesis is assumed. -/
theorem trdeg_le_of_finite_adjoin_surjective [IsDomain A]
    (x : Fin s → R) [Module.Finite (Algebra.adjoin K (Set.range x)) R]
    (f : R →ₐ[K] A) (hf : Function.Surjective f) :
    Algebra.trdeg K A ≤ (s : Cardinal) := by
  let :=  integral_over_image_adjoin x f hf
  have h := Algebra.IsAlgebraic.trdeg_le_cardinalMk K
    (Set.range (fun i => f (x i))) (A := A)
  apply h.trans
  simpa using (Cardinal.mk_range_le_lift (f := fun i => f (x i)))

/-- The prime need not be minimal. -/
theorem trdeg_prime_quotient_le (x : Fin s → R)
    [Module.Finite (Algebra.adjoin K (Set.range x)) R]
    (p : Ideal R) [p.IsPrime] :
    Algebra.trdeg K (R ⧸ p) ≤ (s : Cardinal) :=
  trdeg_le_of_finite_adjoin_surjective x (Ideal.Quotient.mkₐ K p)
    (Ideal.Quotient.mkₐ_surjective K p)

/-- Localization of a domain along an injective structure map does not alter
transcendence degree. Faithfulness is explicit rather than inferred from an
arbitrary multiplicative set. -/
theorem trdeg_localization_eq [IsDomain R] [IsDomain A]
    [Algebra R A] [IsScalarTower K R A] [FaithfulSMul R A]
    (M : Submonoid R) [IsLocalization M A] :
    Algebra.trdeg K A = Algebra.trdeg K R := by
  let : Algebra.IsAlgebraic R A := IsLocalization.isAlgebraic A M
  have h := trdeg_add_eq K R (A := A)
  simpa only [trdeg_eq_zero (R := R) (A := A), add_zero] using h.symm

theorem trdeg_fractionRing_eq [IsDomain R] :
    Algebra.trdeg K (FractionRing R) = Algebra.trdeg K R :=
  trdeg_localization_eq (K := K) (nonZeroDivisors R)

theorem trdeg_prime_fractionRing_le (x : Fin s → R)
    [Module.Finite (Algebra.adjoin K (Set.range x)) R]
    (p : Ideal R) [p.IsPrime] :
    Algebra.trdeg K (FractionRing (R ⧸ p)) ≤ (s : Cardinal) := by
  rw [trdeg_fractionRing_eq]
  exact trdeg_prime_quotient_le x p

/-- Polynomial variables contribute exactly their number. -/
theorem trdeg_polynomial_eq [IsDomain R] (k : ℕ) :
    Algebra.trdeg K (MvPolynomial (Fin k) R) = Algebra.trdeg K R + (k : Cardinal) := by
  have h := trdeg_add_eq K R (A := MvPolynomial (Fin k) R)
  simpa using h.symm

/-- A domain localization after adjoining `k` free coordinates respects the
same explicit budget. -/
theorem trdeg_localized_polynomial_le [IsDomain R] [IsDomain A]
    (g k : ℕ) (hg : Algebra.trdeg K R ≤ (g : Cardinal))
    [Algebra (MvPolynomial (Fin k) R) A]
    [IsScalarTower K (MvPolynomial (Fin k) R) A]
    [FaithfulSMul (MvPolynomial (Fin k) R) A]
    (M : Submonoid (MvPolynomial (Fin k) R)) [IsLocalization M A] :
    Algebra.trdeg K A ≤ ((g+k : ℕ) : Cardinal) := by
  rw [trdeg_localization_eq (K := K) M, trdeg_polynomial_eq, Nat.cast_add]
  exact add_le_add hg le_rfl

/-- The nonzero-denominator condition supplies both domain and faithfulness
for the localization, so neither is an additional geometric premise. -/
theorem trdeg_localized_polynomial_le_of_nonzero [IsDomain R]
    (g k : ℕ) (hg : Algebra.trdeg K R ≤ (g : Cardinal))
    [Algebra (MvPolynomial (Fin k) R) A]
    [IsScalarTower K (MvPolynomial (Fin k) R) A]
    (M : Submonoid (MvPolynomial (Fin k) R)) [IsLocalization M A]
    (hM : M ≤ nonZeroDivisors (MvPolynomial (Fin k) R)) :
    Algebra.trdeg K A ≤ ((g+k : ℕ) : Cardinal) := by
  let : IsDomain A := IsLocalization.isDomain_of_le_nonZeroDivisors A hM
  let : FaithfulSMul (MvPolynomial (Fin k) R) A :=
    (faithfulSMul_iff_algebraMap_injective _ _).mpr (IsLocalization.injective A hM)
  exact trdeg_localized_polynomial_le g k hg M

/-- The entire component/free-coordinate/localization bound from the original
module-finite slice certificate. -/
theorem trdeg_prime_localized_polynomial_le
    (x : Fin s → R) [Module.Finite (Algebra.adjoin K (Set.range x)) R]
    (p : Ideal R) [p.IsPrime] (k : ℕ)
    [Algebra (MvPolynomial (Fin k) (R ⧸ p)) A]
    [IsScalarTower K (MvPolynomial (Fin k) (R ⧸ p)) A]
    (M : Submonoid (MvPolynomial (Fin k) (R ⧸ p))) [IsLocalization M A]
    (hM : M ≤ nonZeroDivisors (MvPolynomial (Fin k) (R ⧸ p))) :
    Algebra.trdeg K A ≤ ((s+k : ℕ) : Cardinal) :=
  trdeg_localized_polynomial_le_of_nonzero s k (trdeg_prime_quotient_le x p) M hM

theorem trdeg_prime_polynomial_fractionRing_le
    (x : Fin s → R) [Module.Finite (Algebra.adjoin K (Set.range x)) R]
    (p : Ideal R) [p.IsPrime] (k : ℕ) :
    Algebra.trdeg K (FractionRing (MvPolynomial (Fin k) (R ⧸ p))) ≤
      ((s+k : ℕ) : Cardinal) := by
  rw [trdeg_fractionRing_eq, trdeg_polynomial_eq, Nat.cast_add]
  exact add_le_add (trdeg_prime_quotient_le x p) le_rfl

/-- Finite type gives finitely many components; reducedness is unnecessary. -/
theorem finite_minimalPrimes [Algebra.FiniteType K R] :
    (minimalPrimes R).Finite := by
  let : IsNoetherianRing R := Algebra.FiniteType.isNoetherianRing K R
  exact minimalPrimes.finite_of_isNoetherianRing R

/-- Module finiteness over the stated finite slice implies finite type. -/
theorem finiteType_of_finite_adjoin (x : Fin s → R)
    [Module.Finite (Algebra.adjoin K (Set.range x)) R] : Algebra.FiniteType K R := by
  let S := Algebra.adjoin K (Set.range x)
  let : Algebra.FiniteType K S := Algebra.FiniteType.adjoin_of_finite (Set.finite_range x)
  exact Algebra.FiniteType.trans (inferInstance : Algebra.FiniteType K S)
    (inferInstance : Algebra.FiniteType S R)

theorem finite_minimalPrimes_of_finite_adjoin (x : Fin s → R)
    [Module.Finite (Algebra.adjoin K (Set.range x)) R] :
    (minimalPrimes R).Finite := by
  let :=  finiteType_of_finite_adjoin (K := K) x
  exact finite_minimalPrimes (K := K)

/-- There are finitely many components and every component function field
obeys the specified slice budget. No reducedness assumption is needed. -/
theorem finite_components_bound (x : Fin s → R)
    [Module.Finite (Algebra.adjoin K (Set.range x)) R] :
    (minimalPrimes R).Finite ∧
      ∀ p ∈ minimalPrimes R,
        Algebra.trdeg K (FractionRing (R ⧸ p)) ≤ (s : Cardinal) := by
  refine ⟨finite_minimalPrimes_of_finite_adjoin (K := K) x, ?_⟩
  intro p hp
  let : p.IsPrime := hp.isPrime
  exact trdeg_prime_fractionRing_le x p

end Quartic.AlgebraicDomainDimension
