module

public import Quartic.GenericF13Endpoint
public import Quartic.QuotientBilinearImage

@[expose] public section

/-!
# Fixed ambient multiplication behind convolution quotient expansion

The actual degree-one relation space is generated by the convolution columns,
and its full quadratic product image is exactly the degree-three relation
space. Quotient expansion can therefore be expressed as expansion of ambient
planes containing those columns, with the proved relation-dimension shift.
-/
noncomputable section
namespace Quartic.ConvolutionAmbientImage
open Module MvPolynomial ConvolutionFree ConvolutionFreePieces
open ConvolutionFreeMultiplication GenericF13Endpoint
variable {K : Type*} [Field K] {t w : ℕ}

/-- Actual quadratic multiplication on the three ambient rows. -/
def multiplication : Forms K (t+w) 2 →ₗ[K] Target K t w 1 →ₗ[K] Target K t w 3 where
  toFun := rowMul
  map_add' f g := by
    apply LinearMap.ext
    intro v
    funext r
    apply Subtype.ext
    change (f.val + g.val) * (v r).val = f.val * (v r).val + g.val * (v r).val
    ring
  map_smul' s f := by
    apply LinearMap.ext
    intro v
    funext r
    apply Subtype.ext
    change (s • f.val) * (v r).val = s • (f.val * (v r).val)
    exact smul_mul_assoc s f.val (v r).val

/-- Each convolution column is an actual degree-one presentation relation. -/
theorem column_mem (k : Fin (t+2)) : convolutionMixed K t w k ∈ relations K t w 1 := by
  classical
  rw [relations_succ]
  let oneForm : Forms K (t+w) 0 := ⟨C 1, isHomogeneous_C _ _⟩
  refine ⟨Pi.single k oneForm,?_⟩
  funext r
  apply Subtype.ext
  simp only [presentation_apply_val, convolutionMixed, AddSubmonoidClass.coe_finsetSum]
  apply Finset.sum_congr rfl
  intro i _
  by_cases h : ConvolutionPresentation.columnIndex r i = k
  · simp [h, Pi.single_apply, oneForm]
  · simp [h, Ne.symm h, Pi.single_apply]

/-- The degree-one relation space has no additional generators. -/
theorem relations_one_eq_span : relations K t w 1 = Submodule.span K (Set.range (convolutionMixed K t w)) := by
  classical
  apply le_antisymm
  · intro v hv
    rw [relations_succ] at hv
    obtain ⟨u,rfl⟩ := hv
    have he : presentation u = ∑ k, (u k).val.coeff 0 • convolutionMixed K t w k := by
      funext r
      apply Subtype.ext
      simp only [Finset.sum_apply, Pi.smul_apply, AddSubmonoidClass.coe_finsetSum,
        SetLike.val_smul, smul_eq_C_mul, presentation_apply_val]
      change (∑ i : Fin t, X (Fin.castAdd w i) * (u (ConvolutionPresentation.columnIndex r i)).val) =
        ∑ k : Fin (t+2), C ((u k).val.coeff 0) * (convolutionMixed K t w k r).val
      simp only [convolutionMixed, AddSubmonoidClass.coe_finsetSum, apply_ite,
        ZeroMemClass.coe_zero, Finset.mul_sum, mul_ite, mul_zero]
      rw [Finset.sum_comm]
      simp only [Finset.sum_ite_eq,Finset.mem_univ,ite_true]
      apply Finset.sum_congr rfl
      intro i _
      rw [ConvolutionPresentation.degreeZero_eq_constant]
      simp [mul_comm]
    rw [he]
    apply Submodule.sum_mem
    intro k _
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨k,rfl⟩)
  · apply Submodule.span_le.mpr
    rintro _ ⟨k,rfl⟩
    exact column_mem k

/-- The degree-three presentation is precisely all quadratic multiples of
the actual degree-one presentation space. -/
theorem relations_three_eq_image :
    relations K t w 3 = BilinearImage.image (multiplication (K := K) (t := t) (w := w)) (relations K t w 1) := by
  classical
  apply le_antisymm
  · intro v hv
    rw [relations_succ] at hv
    obtain ⟨u,rfl⟩ := hv
    rw [← multiplication_convolution]
    have he : GeneralF13.multiplication (convolutionMixed K t w) u =
        ∑ k, multiplication (u k) (convolutionMixed K t w k) := by
      funext r
      apply Subtype.ext
      simp only [GeneralF13.multiplication_val,Finset.sum_apply,AddSubmonoidClass.coe_finsetSum]
      apply Finset.sum_congr rfl
      intro k _
      change (convolutionMixed K t w k r).val * (u k).val = (u k).val * (convolutionMixed K t w k r).val
      ring
    rw [he]
    apply Submodule.sum_mem
    intro k _
    exact BilinearImage.product_mem _ _ (u k) _ (column_mem k)
  · apply iSup_le
    intro f
    rintro _ ⟨v,hv,rfl⟩
    exact rowMul_maps_relations f hv

 theorem relations_one_finrank (ht : 2 ≤ t) : finrank K (relations K t w 1) = t+2 := by
  rw [relations_succ,LinearMap.finrank_range_of_inj (presentation_injective ht (by omega : 0 ≤ 2))]
  simp [Source,Module.finrank_pi_fintype,finrank_forms]

 theorem relations_three_finrank (ht : 2 ≤ t) :
    finrank K (relations K t w 3) = (t+2)*(t+w+1).choose 2 := by
  rw [relations_succ,LinearMap.finrank_range_of_inj (presentation_injective ht (by omega : 2 ≤ 2))]
  simp [Source,Module.finrank_pi_fintype,finrank_forms,Nat.add_assoc]

/-- Actual quotient multiplication has exactly the projected ambient image. -/
theorem image_eq_map (L : Submodule K (Piece K t w 1)) :
    ConvolutionProfileImage.quadraticImage L =
      (BilinearImage.image multiplication (L.comap (relations K t w 1).mkQ)).map (relations K t w 3).mkQ := by
  exact QuotientBilinearImage.image_eq_map multiplication (relations K t w 1) (relations K t w 3)
    ConvolutionInitialImage.pieceBilinear (fun _ _ => rfl) L

 theorem image_finrank_add (L : Submodule K (Piece K t w 1)) :
    finrank K (ConvolutionProfileImage.quadraticImage L) + finrank K (relations K t w 3) =
      finrank K (BilinearImage.image multiplication (L.comap (relations K t w 1).mkQ)) := by
  rw [image_eq_map]
  apply QuotientBilinearImage.finrank_map_mkQ_add
  rw [relations_three_eq_image]
  exact QuotientBilinearImage.image_mono multiplication (QuotientBilinearImage.le_preimage _ L)

/-- Quotient expansion is exactly ambient expansion on planes containing
all actual convolution columns, with the explicit relation dimension shift. -/
theorem expansion_iff_ambient (ht : 2 ≤ t) (d e : ℕ) :
    (∀ L : Submodule K (Piece K t w 1), finrank K L = d →
      e ≤ finrank K (ConvolutionProfileImage.quadraticImage L)) ↔
    (∀ S : Submodule K (Target K t w 1),
      Submodule.span K (Set.range (convolutionMixed K t w)) ≤ S →
      finrank K S = d + (t+2) →
      e + (t+2)*(t+w+1).choose 2 ≤ finrank K (BilinearImage.image multiplication S)) := by
  rw [← relations_one_eq_span]
  constructor
  · intro h S hES hS
    let L := S.map (relations K t w 1).mkQ
    have hL : finrank K L = d := by
      have hdim := QuotientBilinearImage.finrank_map_mkQ_add _ _ hES
      rw [relations_one_finrank ht] at hdim
      dsimp only [L]
      omega
    have hback : L.comap (relations K t w 1).mkQ = S := by
      rw [Submodule.comap_map_mkQ, sup_eq_right.mpr hES]
    have hi := image_finrank_add L
    rw [hback,relations_three_finrank ht] at hi
    have hb := h L hL
    omega
  · intro h L hL
    have hdim := QuotientBilinearImage.finrank_preimage (relations K t w 1) L
    rw [hL,relations_one_finrank ht] at hdim
    have hb := h (L.comap (relations K t w 1).mkQ)
      (QuotientBilinearImage.le_preimage _ L) hdim
    have hi := image_finrank_add L
    rw [relations_three_finrank ht] at hi
    omega

end Quartic.ConvolutionAmbientImage
