module

public import Quartic.Counts

@[expose] public section

/-!
# The strict numerical inequality in cubic independence

The incidence proof in `cubic_lemma.tex` needs the dimension of the cubics
divisible by a `t`-dimensional space of linear forms to exceed the dimension
of the corresponding projective relation stratum. This file proves that
actual integer inequality for every allowed parameter, using a nonnegative
factorization instead of differentiating a rational function.
-/

namespace Quartic.CubicInequality

open Quartic.Counts

/-- Dimension of the degree-three ideal generated by `t` independent linear
forms inside a polynomial ring on `m` variables. -/
def imageDimension (m t : ℕ) : ℤ := b3 m - b3 (m - t)

/-- Exact integral factorization of the incidence gap, after removing its
strictly positive projectivization margin. -/
theorem scaled_incidence_gap (m q t : ℕ) (ht : t ≤ m) :
    6 * (imageDimension m t - (t : ℤ) * ((m : ℤ) + q - t)) =
      (t : ℤ) * (((m : ℤ) + 1) * ((m : ℤ) + 2) - 6 * q) +
      (t : ℤ) * ((m : ℤ) - t) * (2 * (m : ℤ) - t - 3) := by
  have hm := b3_scaled m
  have hmt := b3_scaled (m - t)
  rw [Int.ofNat_sub ht] at hmt
  unfold imageDimension
  linear_combination hm - hmt

/-- The cubic budget forces the unscaled quadratic factor to be nonnegative. -/
theorem budget_factor_nonnegative (m q : ℕ) (hm : 0 < m)
    (hq : (m : ℤ) * q ≤ b3 m) :
    0 ≤ ((m : ℤ) + 1) * ((m : ℤ) + 2) - 6 * q := by
  have hmz : (0 : ℤ) < m := by exact_mod_cast hm
  have hb := b3_scaled m
  have hfactor : 6 * (q : ℤ) ≤ ((m : ℤ) + 1) * ((m : ℤ) + 2) := by
    apply (mul_le_mul_iff_right₀ hmz).mp
    nlinarith only [hb, hq]
  exact sub_nonneg.mpr hfactor

/-- The affine incidence gap is nonnegative; this includes the harmless
case `t = 0`. -/
theorem incidence_gap_nonnegative (m q t : ℕ) (hm : 3 ≤ m) (ht : t ≤ m)
    (hq : (m : ℤ) * q ≤ b3 m) :
    0 ≤ imageDimension m t - (t : ℤ) * ((m : ℤ) + q - t) := by
  have hbudget := budget_factor_nonnegative m q (by omega) hq
  have hmt : (0 : ℤ) ≤ (m : ℤ) - t := by omega
  have hlast : (0 : ℤ) ≤ 2 * (m : ℤ) - t - 3 := by omega
  have ht0 : (0 : ℤ) ≤ t := by positivity
  have hfirst := mul_nonneg ht0 hbudget
  have hsecond := mul_nonneg (mul_nonneg ht0 hmt) hlast
  have hid := scaled_incidence_gap m q t ht
  omega

/-- The strict integer inequality required to exclude every cubic relation
stratum in `cubic_lemma.tex`. -/
theorem cubic_incidence_inequality (m q t : ℕ)
    (hm : 3 ≤ m) (ht : t ≤ m)
    (hq : m * q ≤ Nat.choose (m + 2) 3) :
    0 < imageDimension m t - (t : ℤ) * ((m : ℤ) + q - t) + 1 := by
  have hqz : (m : ℤ) * q ≤ b3 m := by
    unfold b3
    exact_mod_cast hq
  have hgap := incidence_gap_nonnegative m q t hm ht hqz
  omega

/-- Equivalent comparison with the projective parameter count. -/
theorem image_dimension_gt_relation_parameters (m q t : ℕ)
    (hm : 3 ≤ m) (ht : t ≤ m)
    (hq : m * q ≤ Nat.choose (m + 2) 3) :
    (t : ℤ) * ((m : ℤ) + q - t) - 1 < imageDimension m t := by
  have h := cubic_incidence_inequality m q t hm ht hq
  omega

end Quartic.CubicInequality
