import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Data.Finsupp.Multiset
import Mathlib.Data.Sym.Card
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Quotient.Basic
import Mathlib.Tactic

/-!
# Polynomial spaces for quartic multiplication

These definitions use actual homogeneous multivariate polynomials. The final
universal witness statement is a proposition to be proved, not an axiom or an
assumption disguised as a theorem.
-/

noncomputable section

namespace Quartic

open MvPolynomial Module

variable (K : Type*) [Field K] (n d : ℕ)

abbrev Poly := MvPolynomial (Fin n) K

abbrev Forms := MvPolynomial.homogeneousSubmodule (Fin n) K d

/-- Degree-`d` exponent vectors are multisets of `d` variable indices. -/
def exponentEquiv : Sym (Fin n) d ≃ {e : Fin n →₀ ℕ // e.degree = d} :=
  Sym.equivNatSum (Fin n) d

/-- A monomial basis of the actual homogeneous polynomial subspace. -/
def formsBasis : Basis (Sym (Fin n) d) K (Forms K n d) := by
  rw [Forms, MvPolynomial.homogeneousSubmodule_eq_finsupp_supported]
  exact (MvPolynomial.basisRestrictSupport K {e : Fin n →₀ ℕ | e.degree = d}).reindex
    (exponentEquiv n d).symm

instance formsFinite : Module.Finite K (Forms K n d) :=
  Module.Finite.of_basis (formsBasis K n d)

/-- Stars and bars, now as a dimension theorem for polynomial spaces. -/
theorem finrank_forms : finrank K (Forms K n d) = (n + d - 1).choose d := by
  rw [Module.finrank_eq_card_basis (formsBasis K n d), Sym.card_sym_eq_choose]
  simp

theorem finrank_quadrics : finrank K (Forms K n 2) = (n + 1).choose 2 := by
  simpa using finrank_forms K n 2

theorem finrank_quartics : finrank K (Forms K n 4) = (n + 3).choose 4 := by
  simpa using finrank_forms K n 4

/-- Products of quadrics in `Q` by arbitrary quadratic polynomials. -/
def quarticProducts (Q : Submodule K (Poly K n)) : Submodule K (Forms K n 4) :=
  (Q * Forms K n 2).comap (Forms K n 4).subtype

/-- The degree-four quotient. For quadratic `Q`, this is the degree-four
component of the quotient by the ideal generated by `Q`. -/
abbrev QuarticQuotient (Q : Submodule K (Poly K n)) :=
  (Forms K n 4) ⧸ quarticProducts K n Q

/-- The manuscript's nonnegative expected dimension, with integer subtraction. -/
def expectedDimension (r : ℕ) : ℕ :=
  ((n + 3).choose 4 : ℤ) - (r : ℤ) * (n + 1).choose 2 + (r.choose 2 : ℤ) |>.toNat

/-- A concrete characteristic-zero witness for a particular generator count.
Turning existence of such witnesses into a generic statement also requires
the nonempty Zariski-open rank argument. -/
def QuarticWitness (r : ℕ) : Prop :=
  ∃ Q : Submodule K (Poly K n),
    Q ≤ Forms K n 2 ∧ finrank K Q = r ∧
    finrank K (QuarticQuotient K n Q) = expectedDimension n r

/-- This is the remaining universal witness target, not a proved theorem. -/
def MainWitnessStatement : Prop :=
  ∀ n : ℕ, 1 ≤ n → ∀ r : ℕ, r ≤ (n + 1).choose 2 → QuarticWitness K n r

variable {K n}

theorem quadratic_products_homogeneous (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) : Q * Forms K n 2 ≤ Forms K n 4 :=
  (mul_le_mul_left hQ _).trans (MvPolynomial.homogeneousSubmodule_mul 2 2)

theorem quarticProducts_mono {Q Q' : Submodule K (Poly K n)} (h : Q ≤ Q') :
    quarticProducts K n Q ≤ quarticProducts K n Q' :=
  Submodule.comap_mono (mul_le_mul_left h _)

@[simp] theorem quarticProducts_bot : quarticProducts K n ⊥ = ⊥ := by
  simp [quarticProducts]

theorem quadrics_mul_quadrics : Forms K n 2 * Forms K n 2 = Forms K n 4 := by
  calc
    Forms K n 2 * Forms K n 2 = Forms K n 1 ^ 2 * Forms K n 1 ^ 2 := by
      simp only [Forms, MvPolynomial.homogeneousSubmodule_one_pow]
    _ = Forms K n 1 ^ 4 := (pow_add _ 2 2).symm
    _ = Forms K n 4 := MvPolynomial.homogeneousSubmodule_one_pow K 4

@[simp] theorem quarticProducts_all : quarticProducts K n (Forms K n 2) = ⊤ := by
  simp [quarticProducts, quadrics_mul_quadrics]

theorem quotient_vanishes_of_extension {Q Q' : Submodule K (Poly K n)}
    (h : Q ≤ Q') (hQ : quarticProducts K n Q = ⊤) :
    quarticProducts K n Q' = ⊤ := by
  apply top_unique
  rw [← hQ]
  exact quarticProducts_mono h

theorem zero_generator_witness : QuarticWitness K n 0 := by
  refine ⟨⊥, bot_le, by simp, ?_⟩
  change finrank K ((Forms K n 4) ⧸ quarticProducts K n ⊥) = expectedDimension n 0
  rw [quarticProducts_bot]
  rw [(Submodule.quotEquivOfEqBot (⊥ : Submodule K (Forms K n 4)) rfl).finrank_eq]
  simp [expectedDimension, finrank_quartics]

/-- Multiplication by an actual homogeneous quadratic, with its correct graded target. -/
def mulQuadratic (f : Forms K n 2) : Forms K n 2 →ₗ[K] Forms K n 4 where
  toFun a := ⟨f.val * a.val, f.property.mul a.property⟩
  map_add' a b := Subtype.ext (mul_add f.val a.val b.val)
  map_smul' k a := Subtype.ext (mul_smul_comm k f.val a.val)

theorem mulQuadratic_injective (f : Forms K n 2) (hf : f.val ≠ 0) :
    Function.Injective (mulQuadratic f) := by
  intro a b hab
  apply Subtype.ext
  exact mul_left_cancel₀ hf (congrArg Subtype.val hab)

theorem range_mulQuadratic (f : Forms K n 2) :
    LinearMap.range (mulQuadratic f) = quarticProducts K n (Submodule.span K {f.val}) := by
  ext z
  constructor
  · rintro ⟨a, rfl⟩
    exact Submodule.mem_span_singleton_mul.mpr ⟨a.val, a.property, rfl⟩
  · intro hz
    obtain ⟨a, ha, hfa⟩ := Submodule.mem_span_singleton_mul.mp hz
    exact ⟨⟨a, ha⟩, Subtype.ext hfa⟩

/-- Every nonzero quadratic has the predicted degree-four quotient dimension. -/
theorem single_quadric_quotient (f : Forms K n 2) (hf : f.val ≠ 0) :
    finrank K (QuarticQuotient K n (Submodule.span K {f.val})) = expectedDimension n 1 := by
  have hdim : finrank K (quarticProducts K n (Submodule.span K {f.val})) =
      (n + 1).choose 2 := by
    rw [← range_mulQuadratic]
    exact (LinearMap.finrank_range_of_inj (mulQuadratic_injective f hf)).trans
      (finrank_quadrics K n)
  have h := (quarticProducts K n (Submodule.span K {f.val})).finrank_quotient_add_finrank
  rw [hdim, finrank_quartics] at h
  change finrank K ((Forms K n 4) ⧸ quarticProducts K n (Submodule.span K {f.val})) = _
  simp only [expectedDimension, Nat.choose_eq_zero_of_lt (by omega : 1 < 2),
    Nat.cast_zero, Nat.cast_one, one_mul, add_zero]
  omega

theorem single_quadric_witness (f : Forms K n 2) (hf : f.val ≠ 0) : QuarticWitness K n 1 := by
  refine ⟨Submodule.span K {f.val}, ?_, finrank_span_singleton hf, single_quadric_quotient f hf⟩
  exact (Submodule.span_singleton_le_iff_mem f.val (Forms K n 2)).mpr f.property

theorem one_generator_witness (hn : 1 ≤ n) : QuarticWitness K n 1 := by
  let i : Fin n := ⟨0, by omega⟩
  let f : Forms K n 2 := ⟨MvPolynomial.X i ^ 2, MvPolynomial.isHomogeneous_X_pow i 2⟩
  exact single_quadric_witness f (pow_ne_zero _ (MvPolynomial.X_ne_zero i))

end Quartic
