import Quartic.Homogeneous
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.Isomorphisms

/-!
# The degree-four piece of the actual polynomial quotient

For a subspace of homogeneous quadrics, the degree-four elements of its
polynomial ideal are precisely its products with homogeneous quadrics. This
identifies `QuarticQuotient` with the degree-four image in the ring quotient.
-/

noncomputable section

namespace Quartic

open MvPolynomial

variable {K : Type*} [Field K] {n : ℕ}

/-- Projecting a product with a homogeneous quadratic to degree four projects
its other factor to degree two. -/
theorem homogeneousComponent_four_mul_quadratic (f p : Poly K n)
    (hf : f.IsHomogeneous 2) :
    homogeneousComponent 4 (f * p) = f * homogeneousComponent 2 p := by
  induction p using MvPolynomial.induction_on' with
  | monomial e a =>
      have he : (monomial e a : Poly K n).IsHomogeneous e.degree :=
        isHomogeneous_monomial a rfl
      rw [homogeneousComponent_of_mem (hf.mul he), homogeneousComponent_of_mem he]
      by_cases h : e.degree = 2
      · simp [h]
      · have h4 : ¬4 = 2 + e.degree := by omega
        simp [Ne.symm h, h4]
  | add p q hp hq => simp only [mul_add, map_add, hp, hq]

/-- Homogeneous degree four detects only quadratic multipliers, even for an
arbitrary expression in the ideal generated by `Q`. -/
theorem homogeneousComponent_four_mem_products (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) {p : Poly K n}
    (hp : p ∈ Ideal.span (Q : Set (Poly K n))) :
    homogeneousComponent 4 p ∈ Q * Forms K n 2 := by
  have hall : ∀ a : Poly K n, homogeneousComponent 4 (a * p) ∈ Q * Forms K n 2 := by
    induction hp using Submodule.span_induction with
    | mem f hf =>
        intro a
        rw [mul_comm a f, homogeneousComponent_four_mul_quadratic f a (hQ hf)]
        exact Submodule.mul_mem_mul hf (homogeneousComponent_mem 2 a)
    | zero =>
        intro a
        simp
    | add p q hp hq ihp ihq =>
        intro a
        rw [mul_add, map_add]
        exact (Q * Forms K n 2).add_mem (ihp a) (ihq a)
    | smul b p hp ih =>
        intro a
        change homogeneousComponent 4 (a * (b * p)) ∈ Q * Forms K n 2
        rw [← mul_assoc]
        exact ih (a * b)
  simpa using hall 1

/-- In degree four, membership in the polynomial ideal is exactly membership
in the quadratic product subspace. -/
theorem quartic_mem_ideal_iff (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) (p : Forms K n 4) :
    p.val ∈ Ideal.span (Q : Set (Poly K n)) ↔ p.val ∈ Q * Forms K n 2 := by
  constructor
  · intro hp
    have h := homogeneousComponent_four_mem_products Q hQ hp
    rwa [homogeneousComponent_eq_self p.property] at h
  · intro hp
    refine Submodule.mul_induction_on hp ?_ ?_
    · intro f hf a ha
      exact Ideal.mul_mem_right _ _ (Ideal.subset_span hf)
    · intro f g hf hg
      exact Ideal.add_mem _ hf hg

/-- Intersection form of the degree-four ideal computation, in the ambient polynomial ring. -/
theorem forms_four_inf_generatedIdeal (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) :
    Forms K n 4 ⊓ (Ideal.span (Q : Set (Poly K n))).restrictScalars K =
      Q * Forms K n 2 := by
  ext p
  constructor
  · rintro ⟨hp4, hpI⟩
    exact (quartic_mem_ideal_iff Q hQ ⟨p, hp4⟩).mp hpI
  · intro hp
    have hp4 := quadratic_products_homogeneous Q hQ hp
    exact ⟨hp4, (quartic_mem_ideal_iff Q hQ ⟨p, hp4⟩).mpr hp⟩

/-- Map a homogeneous quartic to its class in the actual polynomial quotient. -/
def quarticToRingQuotient (Q : Submodule K (Poly K n)) :
    Forms K n 4 →ₗ[K] Poly K n ⧸ Ideal.span (Q : Set (Poly K n)) :=
  (Ideal.Quotient.mkₐ K (Ideal.span (Q : Set (Poly K n)))).toLinearMap.comp
    (Forms K n 4).subtype

theorem ker_quarticToRingQuotient (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) :
    LinearMap.ker (quarticToRingQuotient Q) = quarticProducts K n Q := by
  ext p
  change Ideal.Quotient.mk (Ideal.span (Q : Set (Poly K n))) p.val = 0 ↔
    p.val ∈ Q * Forms K n 2
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact quartic_mem_ideal_iff Q hQ p

/-- The manuscript's quartic quotient is the degree-four image in the
quotient ring by the ideal generated by its quadrics. -/
def quarticQuotientEquivImage (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) :
    QuarticQuotient K n Q ≃ₗ[K] LinearMap.range (quarticToRingQuotient Q) :=
  (Submodule.quotEquivOfEq _ _ (ker_quarticToRingQuotient Q hQ).symm).trans
    (quarticToRingQuotient Q).quotKerEquivRange

/-- The linear equivalence preserves the represented polynomial class. -/
theorem quarticQuotientEquivImage_mk (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) (p : Forms K n 4) :
    (quarticQuotientEquivImage Q hQ (Submodule.Quotient.mk p) :
      Poly K n ⧸ Ideal.span (Q : Set (Poly K n))) =
      Ideal.Quotient.mk (Ideal.span (Q : Set (Poly K n))) p.val := by
  rfl

theorem finrank_quarticQuotient_eq_image (Q : Submodule K (Poly K n))
    (hQ : Q ≤ Forms K n 2) :
    Module.finrank K (QuarticQuotient K n Q) =
      Module.finrank K (LinearMap.range (quarticToRingQuotient Q)) :=
  (quarticQuotientEquivImage Q hQ).finrank_eq

end Quartic
